project:
  type: website
  output-dir: docs

website:
  title: "INvenTree member directory" 
    # - text: "INvenTree"
    #   href: "https://india-inventree.github.io/"
  navbar:
    pinned: true
    left:
      - href: about.qmd
        text: Become a Member
    right:
      - href: https://india-inventree.github.io/
        text: INvenTree Home
        icon: house-door-fill
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:indiainventree@gmail.com"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/India-INvenTree
        rel: me
        target: "_new"
  page-footer:
    border: true
    left: "&#169; 2025 INvenTree"
    center:
      - text: "Code of conduct"
        href: https://india-inventree.github.io/coc
        icon: check-circle
      - text: "Accessibility"
        href: https://india-inventree.github.io/accessibility
        icon: universal-access-circle
      # - text: License
      #   href: license.qmd
    right: "made with ︎♥️ & [Quarto](https://quarto.org)"


format:
  html:
    theme:
      # - cosmo
      - flatly
      - custom.scss
    css: styles.css
    toc: true

