project:
  type: website
  output-dir: docs

website:
  title: "INvenTree"
  navbar:
    logo-href: https://india-inventree.github.io 
    # title: false  
    pinned: true
    left:
      #  - href: https://india-inventree.github.io/
      #    text: INvenTree
       - href: https://india-inventree.github.io/resources.html
         text: "Resources"
         icon: book
       - text: "People"
         icon: person-circle
         menu:
          - text: "Working Group"
            href: https://india-inventree.github.io/team.html
            # icon: list-check
            # icon: puzzle-fill
            icon: tools
          - text: "Member Directory {{< iconify bi cuia:open-in-new-tab-outline size=1.1em >}}"
            href: "https://india-inventree.github.io/members/"
            target: "_new"
            # icon: mortarboard-fill
            icon: person-badge-fill
       - href: https://india-inventree.github.io/join.html
        # text: "<span class='btn btn-primary'>Click here</span>"
         text: "Get Involved"
        # icon: person-add
         icon: sign-merge-left
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:indiainventree@gmail.com"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/India-INvenTree
        rel: me
        target: "_new"
  page-footer:
    border: true
    left: "&#169; 2025 INvenTree"
    center: "[Code of Conduct](https://india-inventree.github.io/coc) | [Attribution](https://india-inventree.github.io/attribution) | [Privacy](https://india-inventree.github.io/privacy) | [Accessibility](https://india-inventree.github.io/accessibility)"
      # - text: "[Code of Conduct](https://india-inventree.github.io/coc)"
      #   href: https://india-inventree.github.io/coc.html
      #   icon: check-circle
      #   target: "_new"
      # - text: "Accessibility"
      #   href: https://india-inventree.github.io/accessibility
      #   icon: universal-access-circle
      # - text: License
      #   href: license.qmd
    right: "made with ︎♥️ & [Quarto](https://quarto.org)"


format:
  html:
    theme:
      # - cosmo
      - flatly
      - custom.scss
    css: styles.css
    toc: true

