project:
  type: website
  output-dir: docs

website:
  title: "members"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Get Involved

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



